# Generated by Django 5.1.6 on 2025-02-23 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10000)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
                ('country', models.CharField(blank=True, max_length=500, null=True)),
                ('journal_name', models.CharField(blank=True, max_length=5000, null=True)),
                ('authors', models.TextField(blank=True, null=True)),
                ('article_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
